name: Build & Push Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

concurrency:
  group: cd-push-lock
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Hadolint (Dockerfile linter)
      run: |
        sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        sudo chmod +x /bin/hadolint

    - name: Lint Dockerfile
      run: hadolint Dockerfile

    - name: Extract Git Commit Hash
      id: vars
      run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$GIT_SHA .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$GIT_SHA

    - name: Clone and push changes to CD
      run: |
        git config --global user.email "ci-bot@lugx-gaming.com"
        git config --global user.name "LUGX Gaming CI Bot"
        git clone https://x-access-token:${{ secrets.CD_PUSH_TOKEN }}@github.com/shananjana/gaming-site-cd.git
        cd gaming-site-cd

        sed -i "s/newTag: .*/newTag: $GIT_SHA/" overlays/dev/frontend/kustomization.yaml

        git add overlays/dev/frontend/kustomization.yaml
        git commit -m "Update analytic-service image tag to ${{ github.sha }}"
        git push origin main
